MileStone_1 - 4 main sections
mahbubul14/tnw-perma pull request #1
Opened 2021-04-06 18:37 UTC by mahbubul14

# TNW Responsive: 

This website is a mock-up of the original [website](https://perma.cc/M5ZV-Q2D6)

The main focus of this project is RWD (Responsive Web Design) and the tools we used includes:
- flexbox
- CSS grid
- media-query
- relative units(rem, em, %)

2021-04-06 19:45 UTC, henatan99 requested changes
# Changes Required :recycle:
Hi there, you have done a lot in this project :muscle: :+1: yet there are some changes to work on. Please go through all the review comments and make the necessary changes.

### Reminder: This is your first review and you will have only a maximum of two more reviews. If your project doesn't get approved in the third review you will be asked to repeat the project. So, make sure to make all the requested changes before you submit for re-review. 

## To Highlight 
- Nice to implement most of the business requirements
## To Improve [MANDATORY]
- You CSS file has a lot of unnecessary comments, please make your code clean. 
- You have repeated media queries for min-width 768px in your css file. Correct this one. 
- Footer links should be displayed in flex. Please see inline comment 
- Use header tag to wrap the header nav elements. See inline comments. 
- User proper nav tags for the header menu nav items. See inline comments 
- The TNW logo should appear on the first (big) article section as in the original website. See the attached screenshot image. 
![TNW](https://user-images.githubusercontent.com/64894927/113769582-cd5fe800-9729-11eb-9869-9b2e9646942f.png)

- You haven's used the correct red overlay gradient background in the first article of the highlight sections for desktop view. Kindly change the range colors. 
- Date should appear over the first article of the highlights section for desktop view. 
- For proper semantic tags, see the inline comments and make changes accordingly. 

## [OPTIONAL] improvements
- You can improve on typography, but this change is not mandatory 
- Try as much as possible to make your page resembles the original one 

### Kindly make the requested changes and submit for re-review.

### Happy coding :computer: :computer_mouse: 

Should you have any query, find me via: 
[LinkedIn](https://www.linkedin.com/in/henok-mekonnen-2a251613/) | [Twitter](twitter.com/henatan99) | Henok Mekonnen on Slack

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +					<ul>
use flex styling for this element

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +		<nav class="d-flex">
This nav tag should be changes to header tag

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +					<div class="nav-top-row-1-container">
This div tag should be changed to nav tag. Apply the same change for nav-top-row-2 class element too.

2021-04-06 19:45 UTC, henatan99 commented on style.css
> +  width: 100%;
Use absolute unit like px here. This one is distorting the logo image when the view width changes.

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +			<header class="funding-header">
don't use header tag here

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +				<ul>
wrap this ul element with nav tag

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +					<div class="p1">
Use heading tag (hx) for all the titles of article elements in the latest funding section.

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +				<div class="footer-links">
change this div tag to nav tag

2021-04-06 19:45 UTC, henatan99 commented on index.html
> +				<div class="footer-icon">
change this div tag to nav tag

2021-04-07 10:39 UTC, MkrtichSargsyan commented on index.html
> +						<a href="#"
Don't use the header tag here.

2021-04-07 10:49 UTC, MkrtichSargsyan requested changes
## _Status:_ Changes Requested :recycle:

## Hello Guys

Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved


- [x] You still have a header tag inside the article

<hr>

## OPTIONAL

- [x] Add h1 tag to the page

  theoretically and logically wrong to have subheadlines ```<h2>``` without a main headline ```<h1>```,   but it won't have a negative effect.

- [x] you have a horizontal scrollbar on your page. You can fix that by removing ```width: 100vw;``` from the body


Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

2021-04-07 12:58 UTC, MuriloRoque approved these changes
## Status: Approved :green_circle: 

### Hello @mahbubul14 and @SamanAtashi :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2021-04-08 07:36 UTC, merged